// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-public-showcase-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
var list_public_showcase_events_default = defineTool({
  name: "list_public_showcase_events",
  title: "List public showcase events",
  description: "List published wedding/event pages that opted into the public showcase. Returns event type, slug, couple/host names, event date and venue.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of events to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("wedding_details").select(
      "slug,event_type,bride_name,groom_name,wedding_date,venue_name,venue_address"
    ).eq("is_public_showcase", true).eq("tenant_status", "active").not("slug", "is", null).order("wedding_date", { ascending: true }).limit(limit);
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-event-details.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_event_details_default = defineTool2({
  name: "get_event_details",
  title: "Get event details",
  description: "Fetch the public details of a wedding/event page by its event_type (e.g. 'casamento', 'aniversario') and slug. Returns couple names, date, venue, story and public message.",
  inputSchema: {
    event_type: z2.string().min(1).describe("Event type segment from the URL, e.g. 'casamento' or 'aniversario'."),
    slug: z2.string().min(1).describe("Unique event slug from the URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_type, slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("wedding_details").select(
      "slug,event_type,bride_name,groom_name,wedding_date,venue_name,venue_address,venue_map_url,story,couple_message,invitation_message,theme_id,is_public_showcase,tenant_status"
    ).eq("event_type", event_type).eq("slug", slug).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    if (!data || data.tenant_status !== "active" || !data.is_public_showcase) {
      return {
        content: [
          {
            type: "text",
            text: "Event not found or not publicly available."
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "convite-de-evento-mcp",
  title: "Convite de Evento MCP",
  version: "0.1.0",
  instructions: "Tools for browsing public wedding and event invitation pages hosted on Convite de Evento. Use `list_public_showcase_events` to discover events that opted into the public showcase, then `get_event_details` to fetch a specific event by event_type and slug.",
  tools: [list_public_showcase_events_default, get_event_details_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
